# Generated by Django 6.0.5 on 2026-05-26 09:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('assigned_county', models.CharField(choices=[('garissa', 'Garissa (HQ)'), ('wajir', 'Wajir'), ('marsabit', 'Marsabit'), ('isiolo', 'Isiolo'), ('mandera', 'Mandera'), ('samburu', 'Samburu')], default='garissa', max_length=50)),
                ('field_photo', models.ImageField(upload_to='field_verification_photos/')),
                ('is_location_valid', models.BooleanField(default=False)),
                ('verification_message', models.TextField(blank=True, null=True)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_logs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
