# Generated by Django 6.0.5 on 2026-05-26 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fieldguard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancelog',
            name='assigned_county',
            field=models.CharField(default='garissa', max_length=50),
        ),
    ]
